In [3]:
import pandas as pd
import pymongo

data=pd.read_csv('data.csv')
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [4]:
# df should be converted into dict before we push it to mongodb

data = data.to_dict(orient='records')

In [5]:
DB_NAME = "winedata"
COLLECTION_NAME = "datasets_wine"
CONNECTION_URL="mongodb+srv://sofianelkwahi1937:A2TnYcfoed4GSmy0@cluster0.prykgrv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

In [6]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

In [7]:
# Uploading data to MongoDB
rec = collection.insert_many(data)

In [8]:
# Load back data from mongodb

df = pd.DataFrame(list(collection.find()))
df.head(2)

,_id,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,683a414558a30fd0c22aa785,7.4,0.70,0.0,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,683a414558a30fd0c22aa786,7.8,0.88,0.0,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1